#:kivy 1.8.0
#:import Factory kivy.factory.Factory
#:import NoTransition kivy.uix.screenmanager.NoTransition

<ActionSpinnerOptions@SpinnerOption>
    background_color: .4, .4, .4, 1

<ActionSpinner@Spinner+ActionItem>
    canvas.before:
        Color:
            rgba: 0.128, 0.128, 0.128, 1
        Rectangle:
            size: self.size
            pos: self.pos
    border: 27, 20, 12, 12
    background_normal: 'atlas://data/images/defaulttheme/action_group'
    option_cls: Factory.ActionSpinnerOptions

<ActionDropdown>:
    on_size: self.width = '220dp'

<ShowcaseScreen>:
    BoxLayout:
        id: content
        orientation: 'vertical'
        
<SaveDialog>:
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
            on_selection: text_input.text = self.selection and self.selection[0] or ''

        TextInput:
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(filechooser.path, text_input.text)

    
    
#    ScrollView:
#        do_scroll_x: False
#        do_scroll_y: False if root.fullscreen else (content.height > root.height - dp(16))
#        AnchorLayout:
#            id: content
#            size_hint_y: None
#            height: root.height if root.fullscreen else max(root.height, content.height)
#            GridLayout:
#                id: content
#                cols: 1
#                spacing: '8dp'
#                padding: '8dp'
#                size_hint: (1, 1) if root.fullscreen else (.8, None)
#                height: self.height if root.fullscreen else self.minimum_height


<Hide_ActionPreviousIcon@ActionPrevious>:

    title: '' if not app.current_title else '{}'.format(app.current_title)
    with_previous: False
    app_icon: ''
    app_icon_width: 0
    app_icon_height: 0
#    size_hint_x: None
#    width: len(self.title)


#<Hide_ActionPrevious@ActionPrevious>:
#    with_previous: False
#    on_press: print(self)
#    title: ''
#    app_icon: ''
#    app_icon_width: 0
#    app_icon_height: 0

BoxLayout:
    orientation: 'vertical'

    canvas.before:
        Color:
            rgb: .6, .6, .6
        Rectangle:
            size: self.size
            source: 'data/background.png'

    ActionBar:

        ActionView:
            id: av
            
            Hide_ActionPreviousIcon:

#            ActionPrevious:
#                with_previous: (False if not app.current_title else True) if sm.current_screen else False
#                title: 'Showcase' + ('' if not app.current_title else ' - {}'.format(app.current_title))
#               on_release: app.go_hierarchy_previous()


            ActionSpinner:
                id: spnr
                important: True
                text: 'Jump to Screen'
                values: app.screen_names
                on_text:
                    if (sm.current != args[1]) and (args[1])!='Jump to ...':\
                    idx = app.screen_names.index(args[1]);\
                    app.go_screen(idx);\
                    self.text = 'Jump to ...'
            ActionButton:
                text: 'Previous screen'
                icon: 'data/icons/chevron-left.png'
                on_release: app.go_previous_screen()

            ActionButton:
                text: 'Next screen'
                icon: 'data/icons/chevron-right.png'
                on_release: app.go_next_screen()
                important: True

    ScreenManager:
        transition: NoTransition()
        id: sm
        on_current_screen:
            spnr.text = args[1].name
            idx = app.screen_names.index(args[1].name)
            if idx > -1: app.hierarchy.append(idx)

                
    