#:import Factory kivy.factory.Factory


Acquisition:
    name: 'Acquisition'
    fullscreen: True

    ScreenManager:
        id: sm

        Screen:
            name: 'Idle'
            canvas.before:
                Color:
                    rgb: .8, .2, .2
                Rectangle:
                    size: self.size
                
            AnchorLayout:
                Button:
                    size_hint: None, None
                    size: '150dp', '48dp'
                    text: 'Start Acquistion'
                    on_release: root.show_save()
        Screen:
            name: 'Acquisition'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    orientation:'horizontal'
                    id: hor_layout1
                    size_hint_y: None
                    height: self.parent.height * 15 /16
           
                    BoxLayout:
                        orientation: 'vertical'
                        size_hint_x: 1
                        size_hint_y: 1
                        id: checkbox_layout
                        
                        canvas.before:
                            Color:
                                rgba: 1, 1, 1, 1  # Set the background color to white
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        #
                        #BoxLayout:
                        #    orientation: 'horizontal'
                        #    CheckBox:
                        #    Label:
                        #        size_hint_x:4
                        #        text: 'beta'
                        #BoxLayout:
                        #    orientation: 'horizontal'
                        #    CheckBox:
                        #    Label:
                        #        size_hint_x:5
                        #        text: 'gamma'

        
                    BoxLayout:
                        id:plot_layout
                        orientation: 'vertical'
                        size_hint_x: 7
                        
                        #Label:
                        #    text: "Data plot here"
                        #    font_size: 10
                        # Add your matplotlib graph widget here
                        # For example, you can use a FigureCanvasKivyagg widget.
            
                BoxLayout:
                    orientation: 'horizontal'
                    id: hor_layout2
                    size_hint_y: None
                    height: self.parent.height * 1 /16
        
                    Label:
                        id: filename_label
                        text: 'File name here'
                        size_hint_x: 4
        
                    Button:
                        size_hint_x: 1
                        text: 'Stop Acquisition'
                        on_release: root.stop_acquisition()
