ShowcaseScreen:
    canvas:
        Color:
            rgba: 1,0,0,0.2
        Rectangle:
            pos: self.pos
            size: self.size
    name: 'Buttons'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button normal'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button down'
        state: 'down'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button disabled'
        disabled: True

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Button down disabled'
        state: 'down'
        disabled: True
    Label:       
        canvas:
            
            Color:
                rgba: 0,0,1,0.2
            Rectangle:
                pos: self.pos
                size: self.size
                
        text:'Gamma counts here'
